name: fleet-care
services:
  fleet-care-db:
    image: postgres:16-alpine
    container_name: fleet-care-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fleetcare
      - POSTGRES_PASSWORD=fleetcare
      - POSTGRES_DB=fleet-care-db