spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet-care-db
    username: fleetcare
    password: fleetcare
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always