CREATE TABLE IF NOT EXISTS vehicle_types (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(12) NOT NULL,-- TODO это enum
    maintenance_interval INT NOT NULL
);

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_type_id BIGINT NOT NULL,
    mileage INT NOT NULL,
    repair_status VARCHAR(15) DEFAULT 'AVAILABLE',
    license_plate VARCHAR(15) NOT NULL,

    CONSTRAINT fk_vehicle_type_id FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    role VARCHAR(15) NOT NULL -- TODO это enum
);

CREATE TABLE IF NOT EXISTS repair_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    comment VARCHAR(500),
    request_status VARCHAR(15), -- TODO это enum, сделать default

    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS repairs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE, -- TODO подумать сразу задавать или сделать эндпоинт(пока за эндпоинт)
    master_id BIGINT NOT NULL,
    request_id BIGINT NOT NULL,
    repair_type VARCHAR(15) NOT NULL, -- TODO это enum
    repair_status VARCHAR(15), -- TODO это, сделать default
    repair_cost DECIMAL(10,2) NOT NULL,

    CONSTRAINT fk_vehicle_id FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
    CONSTRAINT fk_master_id FOREIGN KEY (master_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_request_id FOREIGN KEY (request_id) REFERENCES repair_requests(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS spare_parts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    stock_quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS repair_spare_parts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    repair_id BIGINT NOT NULL,
    spare_part_id BIGINT NOT NULL,
    quantity INT NOT NULL,

    CONSTRAINT fk_repair_id FOREIGN KEY (repair_id) REFERENCES repairs(id) ON DELETE CASCADE,
    CONSTRAINT fk_spare_part_id FOREIGN KEY (spare_part_id) REFERENCES spare_parts(id) ON DELETE CASCADE
);

